model:
  backbone: "shufflenet_v2_x1_0"
  pretrained: true
  gem_p: 3.0  # GeM pooling parameter
  embedding_dim: 512

training:
  num_epochs: 50
  batch_size: 32
  pos_samples: 3
  neg_samples: 3
  learning_rate: 0.0001
  weight_decay: 0.0001
  alpha: 5  # triplet loss margin
  num_mini_batches: 50000

transforms:
  train:
    - name: "RandomHorizontalFlip"
      p: 0.5
    - name: "RandomRotation"
      degrees: 10
    - name: "ColorJitter"
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    - name: "Resize"
      size: [256, 256]
    - name: "ToTensor"
    - name: "Normalize"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

data:
  base_height: 200
  locations:
    - [50.4162, 30.8906]
    - [48.9483, 29.7241]
    - [49.3721, 31.0945]
    - [48.5673, 33.4218]
    - [46.6234, 32.7851]
    - [51.4523, 32.8945]
    - [48.2367, 35.7823]
    - [47.8945, 30.2367] 